GET http://localhost:3003/api/blogs/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY2ZTE0ZjJkYzI3OGQwNmRkMzM1YzA5ZSIsImlhdCI6MTcyNjIwOTgyMywiZXhwIjoxNzI2Mjk2MjIzfQ.kXACeLdBdB2vcmOrKT7KVyIyJJ2Gq_Yp4rfRsdsianI