POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imx1dSIsImlkIjoiNjZkZjFhMTU5NDM3YjAyOWFlMGIyZWJlIiwiaWF0IjoxNzI1OTY4MDg2LCJleHAiOjE3MjYwNTQ0ODZ9.SQ11Th6ObqhswRl5DLB-gjJ-3c7kT5jjdTbqinGNPps

{
    "title": "iPhone 16 Pro Max 2024", 
    "author": "Tim Cook II",
    "url": "iphone.apple.com",
    "likes": 11
}
