services:
  #BE
  backend:
    image: patientor-be-prod
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    # ports:
    #   - 3001:3001
  #FE    
  frontend:
    image: patientor-fe-prod
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    # ports:
    #   - 5173:5173
  #Reverse Proxy
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8686:80
    container_name: reverse-proxy-prod
    depends_on:
      - frontend # wait for the frontend container to be started